# Generated by Django 5.2.1 on 2025-05-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                ("id_ciudad", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("ciudad", models.CharField()),
                ("pais", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id_tipo_documento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("tipo_documento", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("identificacion", models.CharField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("nombre", models.CharField()),
                ("telefono", models.BigIntegerField()),
                ("correo", models.CharField()),
                (
                    "id_ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.ciudad",
                    ),
                ),
                (
                    "id_tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.tipodocumento",
                    ),
                ),
            ],
        ),
    ]
