# Generated by Django 5.2.1 on 2025-05-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("nombre_producto", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                ("id_factura", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("vendedor", models.CharField()),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id_compra", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("cantidad", models.IntegerField()),
                ("valor", models.BigIntegerField()),
                (
                    "id_factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="factura.factura",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="factura.producto",
                    ),
                ),
            ],
        ),
    ]
